import '../common/common.just'

# First app deploymen
[group('deployment')]
initial-deploy: rebuild-helper
    @just generate-env -e prod
    @just generate-pki -e prod
    @docker compose --env-file {{ dotenv-prod }} --env-file {{ pki-dotenv }} up kafka garage -d --wait
    @just _run-task -t pre-init -e prod
    @docker compose --env-file {{ dotenv-prod }} --env-file {{ pki-dotenv }} up --build -d --wait
    @just _run-task -t post-init -e prod

# Stops the application and erases all the stored data (ignores images)
[group('deployment')]
uninstall:
    docker compose --env-file {{ dotenv-prod }} --env-file {{ pki-dotenv }} down -v
    rm {{ dotenv-prod }}

# Erases the stored data and performs a clean deployment
[group('deployment')]
reinstall: uninstall initial-deploy

# Starts the application (use `initial-deploy` for the first run)
[group('lifecycle')]
run:
    docker compose --env-file {{ dotenv-prod }} --env-file {{ pki-dotenv }} up -d

# Stops the application (does not delete data)
[group('lifecycle')]
stop:
    docker compose --env-file {{ dotenv-prod }} --env-file {{ pki-dotenv }} down
